[build]
  command="ng build"
  publish="dist/angular-quickstart"

[[redirects]]
  from = "/Suche.html"
  to = "/Suche.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200